[mypy]
python_version = 3.11
warn_unused_configs = True
explicit_package_bases = True
exclude = (?x)(^addon/globalPlugins/nvdastudio/lib/|^addon/globalPlugins/nvdastudio/nvda_docs_cache/|^venv/|^node_modules/)

[mypy-croniter.*]
ignore_missing_imports = True
